# http://travis-ci.org/#!/strawlab/pymvg
language: python
python:
    - "2.7_with_system_site_packages"
    - "3.4"
    - "3.6"
sudo: false
addons:
    apt:
        packages:
            - python-opencv python-tk python3-tk
install:
    - pip install -r requirements.txt
    - pip install nose-exclude # for --exclude-dir option in call to nosetests
    - pip install coveralls # for coverage testing
    - python setup.py install
script:
    - nosetests --with-doctest --with-coverage --cover-package=pymvg --exclude-dir=test/external --exclude-dir=extern --where=pymvg
    - if [[ $TRAVIS_PYTHON_VERSION == '2.'* ]]; then nosetests --where=pymvg/test/external/opencv; fi
after_success:
    - coveralls
